# TCL File Generated by Component Editor 14.0
# Sun Mar 01 15:45:06 EST 2015
# DO NOT MODIFY


# 
# bexkat1 "bexkat1" v1.3
# Matt Stock 2015.03.01.15:45:06
# Bexkat1 CPU with 32bit data and endian options
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module bexkat1
# 
set_module_property DESCRIPTION "Bexkat1 CPU with 32bit data and endian options"
set_module_property NAME bexkat1
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Matt Stock"
set_module_property DISPLAY_NAME bexkat1
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL bexkat1
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file alu.v VERILOG PATH cpu/alu.v
add_fileset_file intcalc.v VERILOG PATH cpu/intcalc.v
add_fileset_file intsdiv.qip OTHER PATH cpu/intsdiv.qip
add_fileset_file intsdiv.v VERILOG PATH cpu/intsdiv.v
add_fileset_file intsmult.qip OTHER PATH cpu/intsmult.qip
add_fileset_file intsmult.v VERILOG PATH cpu/intsmult.v
add_fileset_file intudiv.qip OTHER PATH cpu/intudiv.qip
add_fileset_file intudiv.v VERILOG PATH cpu/intudiv.v
add_fileset_file intumult.qip OTHER PATH cpu/intumult.qip
add_fileset_file intumult.v VERILOG PATH cpu/intumult.v
add_fileset_file bexkat1.v VERILOG PATH cpu/bexkat1.v TOP_LEVEL_FILE
add_fileset_file registerfile.v VERILOG PATH cpu/registerfile.v


# 
# parameters
# 
add_parameter big_endian STD_LOGIC_VECTOR 1
set_parameter_property big_endian DEFAULT_VALUE 1
set_parameter_property big_endian DISPLAY_NAME big_endian
set_parameter_property big_endian TYPE STD_LOGIC_VECTOR
set_parameter_property big_endian UNITS None
set_parameter_property big_endian ALLOWED_RANGES 0:3
set_parameter_property big_endian HDL_PARAMETER true


# 
# display items
# 


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_read read Output 1
add_interface_port m0 avm_m0_readdata readdata Input 32
add_interface_port m0 avm_m0_writedata writedata Output 32
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_byteenable byteenable Output 4
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 50000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1

